### PR TITLE
fix #1 

### LINKED ISSUE #1: [BUG] manifest does not contains assets.
All assets (include images/css and other) should be list in manifest, not just cover:

https://github.com/CharlesMulloy/epub-builder/blob/master/src/index.ts#L149-L151

If not, some application (like sigil) will delete them.

### PR DESCRIPTION
**Pull request by Cologler**
fix #1

### CODE REVIEW

**Comment by Cologler** [comment]
close #6

**Review by CharlesMulloy — COMMENTED** [review]
What is the eslint file intended to solve? The entire project is written in Typescript, so while the resulting Javascript can be checked against the rules here, I don't see how this can help from a development point of view.

I agree that the all assets need to be added to the manifest if applications are going to behave like that. Thank you for bringing this to my attention. 

I'm still going over the rest of the pull request.

**Comment by Cologler** [comment]
@CharlesMulloy which commit do you review?

* add eslintrc - add eslintrc for eslint
* add all asset into manifest - fixed #1, so google play book can read the images.
* add builder - resolved #6
* docs: change the API - see *add builder*
* add prepare script - for when I use `npm i git+https://github.com/CharlesMulloy/epub-builder.git` to install, npm can auto execute `tsc`.

The project still written in Typescript. what did you mean "The entire project is written in Typescript, so while the resulting Javascript can be checked against the rules here, I don't see how this can help from a development point of view."?

**Comment by Cologler** [comment]
Seems eslint is only for JavaScript ... haha

**Comment by CharlesMulloy** [comment]
I apologize that I have not been able to give your contributions the attention they deserve. I've been preoccupied with other things lately.

After looking at the API (9de4dba) and structure (9ab7ae2) changes you suggested, while I'm hesitant to make changes to it that would likely break any projects that rely on it, npmjs.org only shows that epub-builder was downloaded only 7 times last week so I doubt this will affect very many people at all so I don't really have a problem with that. I'd like to avoid it in the future if possible though. 

I also like the prepare script that you added (12c0799). I was not aware that it is possible to have the project built automatically like this after pulling in the dependencies and thought that the project had to be built manually.

I'm still not keen on the eslint file though (8c952e0 / b1d1406). It did however lead me to look into using a tslint file, that does basically the same thing, but for Typescript files. I plan to implement a tslint file thanks to this suggestion and base it off of the eslintrc file, where appropriate. I see no reason to remove it yet, but it will be replaced in a future commit.

The last commit (86b0d16) is something else that I agree with. I noticed that you pointed out that it won't pass inspection when being validated if a resource is referenced twice, but this will allow us to specify a resource once and still use it as a cover image and book asset.

I plan on merging this sometime tomorrow (barring any objections or problems). There is a test file that neither of us touched that I'd like to update before I push to npmjs. Once the test file is confirmed to be working using all of the features, I'll be confident enough to release to the repository.

You put a lot of hard work into this, and I thank you for all of it. I learned a few things that will be useful elsewhere.

**Comment by Cologler** [comment]
Agreed to remove eslintrc.

Any suggest for the new `EpubBuilder` api ? Is any way to keep both old api and new api ? I found a way to keep it, but it is seems ugly:

1. change `export class EpubBuilder` to `class EpubBuilder`
1. use node export api: `module.exports = new EpubBuilder();`
1. we can use old api: `const book = require("epub-builder");`
1. if we try to use new api, use `const newbook = new (require("epub-builder").constructor);`

**Comment by CharlesMulloy** [comment]
I don't think there's an elegant way to do it. Epub-Builder isn't that popular at the moment so we wouldn't be breaking a whole lot, but this seems like a good start. Keep in mind, I'm trying to keep it as simple as possible, and 9ab7ae2 seemed to do a good enough job. I'd like to avoid having a new way and an old way if possible, but I don't want to alienate those who might be using it already, though there aren't many. It can be re-simplified later once we've made sure everything works. Let's just make sure that the test file works both ways (later commit) and confirmed to be working per the examples in the readme. The readme can link to npmjs so that users can see the latest stable build and instructions. Then it can be published to npmjs after it's confirmed to be working.

I'm going to merge this later today. The merge is big enough as it is and is likely out of scope with what it was intended to fix, but did resolve many issues that I might not have ever caught. Lets save any further commits for later.

**Pull request merged**
